
const API_BASE = 'https://17-539-api-production-9873.up.railway.app';
const API_FALLBACK_BASE = window.location.origin;
const state={token:localStorage.getItem('lottery_admin_token')||'',user:null,members:[],deviceMember:null};
const $=id=>document.getElementById(id);
function msg(t,ok=false){const el=$('loginMsg');if(el){el.textContent=t||'';el.style.color=ok?'#baf57f':'#ffb3b3';}}
function toast(text,type='info'){const wrap=$('toastWrap'); if(!wrap) return; const item=document.createElement('div'); item.className=`toast ${type}`; item.textContent=text||''; wrap.appendChild(item); setTimeout(()=>{ item.remove(); }, 2600);}
function getDeviceId(){let id=localStorage.getItem('lottery_admin_device_id')||'';if(!id){id=`adm_${Math.random().toString(36).slice(2)}_${Date.now().toString(36)}`;localStorage.setItem('lottery_admin_device_id',id)}return id}
function headers(extra={}){const h={...extra,'x-device-id':getDeviceId(),'x-device-name':'admin-console'};if(state.token)h['x-auth-token']=state.token;return h}
function planDays(plan,days){if(plan==='quarter')return 90;if(plan==='year')return 365;if(plan==='custom')return Math.max(1,Number(days||0));if(plan==='permanent')return 36500;return 30}
function fmt(v){return v?String(v).replace('T',' ').slice(0,16):'—'}
function escapeHtml(s){return String(s||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function ipLabel(ip=''){const v=String(ip||'').trim();if(!v)return '未知來源';if(v==='::1'||v==='127.0.0.1'||v.startsWith('127.'))return '本機 localhost';if(v.startsWith('192.168.')||v.startsWith('10.')||/^172\.(1[6-9]|2\d|3[0-1])\./.test(v))return '內網 / 區域網路';if(v.includes(':'))return 'IPv6 網路';return '外部網路'}
function apiTargets(path){ return [`${API_BASE}${path}`, `${API_FALLBACK_BASE}${path}`]; }
async function api(path,options={}){ let lastErr=null; for(const target of apiTargets(path)){ try{ const res=await fetch(target,{cache:'no-store',...options,headers:headers(options.headers||{})}); const raw=await res.text(); let data=null; try{ data=raw?JSON.parse(raw):{} }catch(_){ data={ok:false,message:raw && /<(!doctype|html)/i.test(raw)?`伺服器回傳了網頁內容，請確認 API 部署是否正常：${target}`:'伺服器回應異常'} } if(!res.ok||data?.ok===false) throw new Error(data?.message||`請求失敗(${res.status})`); return data; }catch(err){ lastErr=err; }} throw lastErr||new Error('API 連線失敗'); }
const modalState={resolver:null};
function closeActionModal(){ $('actionModal')?.classList.remove('show'); modalState.resolver=null; }
function showActionModal({title='操作', bodyHtml='', confirmText='確認', cancelText='取消', onConfirm=null}){ return new Promise((resolve)=>{ $('actionModalTitle').textContent=title; $('actionModalBody').innerHTML=bodyHtml; $('actionModalConfirm').textContent=confirmText; $('actionModalCancel').textContent=cancelText; $('actionModal').classList.add('show'); modalState.resolver=resolve; const finish=(ok,payload=null)=>{ $('actionModal').classList.remove('show'); const r=modalState.resolver; modalState.resolver=null; if(r) r(ok?payload:null); }; $('actionModalClose').onclick=()=>finish(false); $('actionModalCancel').onclick=()=>finish(false); $('actionModalConfirm').onclick=async()=>{ try{ const payload=onConfirm?await onConfirm():true; finish(true,payload); }catch(err){ toast(err.message||'操作失敗','warn'); } }; }); }
async function askDeviceLimit(current){ return showActionModal({ title:'調整設備上限', bodyHtml:`<div><label>設備上限</label><select id="deviceLimitSelect"><option value="3">3 台</option><option value="5">5 台</option><option value="8">8 台</option><option value="10">10 台</option></select><div class="actionHelp">可從後台調整一般會員或 VIP 會員的設備優勢。</div></div>`, confirmText:'儲存設定', onConfirm:()=>{ const value=Number($('deviceLimitSelect').value||current||3); if(![3,5,8,10].includes(value)) throw new Error('設備上限只能設定為 3 / 5 / 8 / 10'); return {value}; } }).then(v=>v?.value ?? null).then(v=>{ if(v!==null){ const sel=$('deviceLimitSelect'); if(sel) sel.value=String(v);} return v; }); }
async function askText(title,label,value='',help='',type='text',confirmText='確認'){ return showActionModal({ title, bodyHtml:`<div><label>${label}</label><input id="actionModalInput" type="${type}" value="${escapeHtml(value)}"><div class="actionHelp">${help}</div></div>`, confirmText, onConfirm:()=>{ const next=String($('actionModalInput').value||'').trim(); if(!next) throw new Error('請先輸入內容'); return next; } }); }
async function askExtendPlan(){ const picked=showActionModal({ title:'會員續期', bodyHtml:`<div><label>續期方案</label><select id="extendPlan"><option value="month">月</option><option value="quarter">季</option><option value="year">年</option><option value="custom">自訂天數</option><option value="permanent">永久</option></select></div><div id="extendDaysWrap" style="display:none"><label>自訂天數</label><input id="extendDays" type="number" min="1" value="30"></div><div class="actionHelp">可直接用月 / 季 / 年 / 永久方案，或指定自訂天數。</div>`, confirmText:'確認續期', onConfirm:()=>{ const plan=String($('extendPlan').value||'month'); const days=plan==='custom'?Math.max(1,Number($('extendDays').value||30)):planDays(plan,30); return {plan,days}; } }); setTimeout(()=>{ const sel=$('extendPlan'); const wrap=$('extendDaysWrap'); if(!sel||!wrap) return; const sync=()=>{ wrap.style.display=sel.value==='custom'?'block':'none'; }; sel.onchange=sync; sync(); },0); return picked.then(v=>v||null); }
function showAdmin(){ $('loginView').style.display='none'; $('adminView').classList.add('show'); $('adminBadge').textContent=`${state.user.displayName||state.user.username}｜管理員`; }
function showLogin(){ $('loginView').style.display='block'; $('adminView').classList.remove('show'); }
async function loadIpInfo(){ try{ const d=await api('/api/admin/ip-info'); $('ipInfoText').textContent=`登入來源：${d.label||ipLabel(d.ip)}｜IP：${d.ip||'—'}`; }catch(_){ $('ipInfoText').textContent='登入來源：—'; } }
async function verify(){ if(!state.token) return showLogin(); try{ const data=await api('/api/auth/me'); if(data.user?.role!=='admin') throw new Error('此帳號不是管理員'); state.user=data.user; showAdmin(); await Promise.all([loadMembers(),loadKeys(),loadLogs(),loadIpInfo()]); }catch(err){ localStorage.removeItem('lottery_admin_token'); state.token=''; showLogin(); msg(err.message||'請重新登入'); }}
async function login(){ const username=$('loginUsername').value.trim(); const password=$('loginPassword').value.trim(); if(!username||!password) return msg('請輸入帳號與密碼'); msg('登入中…',true); try{ const data=await api('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password,deviceId:getDeviceId(),deviceName:'admin-console'})}); if(data.user?.role!=='admin') throw new Error('請使用管理員帳號登入後台'); state.token=data.token; localStorage.setItem('lottery_admin_token',data.token); state.user=data.user; msg('登入成功',true); showAdmin(); await Promise.all([loadMembers(),loadKeys(),loadLogs(),loadIpInfo()]); }catch(err){msg(err.message||'登入失敗')}}
async function logout(){ try{await api('/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})}catch(_){ } localStorage.removeItem('lottery_admin_token'); state.token=''; state.user=null; showLogin(); }
async function loadMembers(){ const data=await api('/api/admin/members'); state.members=Array.isArray(data.members)?data.members:[]; $('membersTbody').innerHTML=state.members.map(m=>`<tr><td><div><b>${escapeHtml(m.displayName||m.username)}</b></div><div class="small mono">${escapeHtml(m.username)}<br>ID:${escapeHtml(m.id)}</div></td><td><div>${escapeHtml(m.planType||'month')}</div><div class="small">到期：${escapeHtml(fmt(m.expiresAt))}</div></td><td><div><b>${m.accessLevel==='vip'?'VIP':'一般'}</b></div><div class="small">${m.accessLevel==='vip'?'可用任務/群組通報':'不可用 VIP 功能'}</div></td><td><div><b>${m.deviceCount||0} / ${m.deviceLimit||3}</b></div><div class="small">最多綁定 ${m.deviceLimit||3} 台</div></td><td><div class="${m.status==='disabled'||m.isExpired?'danger':'ok'}">${m.status==='disabled'?'停用':(m.isExpired?'已到期':'正常')}</div></td><td><div class="btns"><button onclick="openDevices('${m.id}')">設備</button><button onclick="extendMember('${m.id}')">續期</button><button onclick="toggleVip('${m.id}','${m.accessLevel==='vip'?'normal':'vip'}')">${m.accessLevel==='vip'?'改一般':'改 VIP'}</button><button onclick="toggleMember('${m.id}','${m.status==='disabled'?'active':'disabled'}')">${m.status==='disabled'?'啟用':'停用'}</button><button onclick="changePassword('${m.id}')">改密碼</button><button onclick="changeDeviceLimit('${m.id}', ${m.deviceLimit||3})">設備上限</button></div></td></tr>`).join('')||'<tr><td colspan="6" class="small">目前沒有會員</td></tr>' }
async function loadKeys(){ const data=await api('/api/admin/access-keys'); const keys=Array.isArray(data.keys)?data.keys:[]; $('keysTbody').innerHTML=keys.map(k=>`<tr><td class="mono">${escapeHtml(k.code)}</td><td>${escapeHtml(k.planType)} / ${Number(k.durationDays||0)}天</td><td>${escapeHtml(k.status)}</td><td>${escapeHtml(k.usedBy||'—')}</td></tr>`).join('')||'<tr><td colspan="4" class="small">沒有金鑰</td></tr>' }
async function loadLogs(){ const data=await api('/api/admin/logs'); const logs=Array.isArray(data.logs)?data.logs:[]; $('logsTbody').innerHTML=logs.map(item=>`<tr><td>${escapeHtml(fmt(item.createdAt))}</td><td>${escapeHtml(item.action)}</td><td>${escapeHtml(item.target||'—')}</td><td>${escapeHtml(item.detail||'—')}</td><td>${escapeHtml(item.actor||'—')}</td></tr>`).join('')||'<tr><td colspan="5" class="small">目前沒有操作日誌</td></tr>'; }
async function createMember(){ const payload={username:$('memberUsername').value.trim(),displayName:$('memberDisplay').value.trim(),password:$('memberPassword').value.trim(),planType:$('memberPlan').value,durationDays:planDays($('memberPlan').value,$('memberDays').value),accessLevel:$('memberAccessLevel').value,deviceLimit:Number($('memberDeviceLimit').value||3),note:$('memberNote').value.trim()}; await api('/api/admin/members',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); ['memberUsername','memberDisplay','memberPassword','memberNote'].forEach(id=>$(id).value=''); $('memberAccessLevel').value='normal'; $('memberDeviceLimit').value='3'; await Promise.all([loadMembers(),loadLogs()]); }
async function generateKeys(){ const payload={planType:$('keyPlan').value,count:Number($('keyCount').value||1),durationDays:planDays($('keyPlan').value,$('keyDays').value),prefix:$('keyPrefix').value.trim()||'SVN'}; await api('/api/admin/access-keys/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); await Promise.all([loadKeys(),loadLogs()]); }
async function redeem(){ await api('/api/admin/access-keys/redeem',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:$('redeemCode').value.trim(),targetUserId:$('redeemUserId').value.trim()})}); await Promise.all([loadMembers(),loadKeys(),loadLogs()]); }
async function extendMember(id){ const picked=await askExtendPlan(); if(!picked) return; await api(`/api/admin/members/${id}/extend`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({planType:picked.plan,durationDays:picked.days})}); await Promise.all([loadMembers(),loadLogs()]); toast('會員續期已更新','ok'); }
async function toggleMember(id,status){ await api(`/api/admin/members/${id}/update`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})}); await Promise.all([loadMembers(),loadLogs()]); toast(status==='disabled'?'會員已停用':'會員已啟用','ok'); }
async function toggleVip(id,accessLevel){ await api(`/api/admin/members/${id}/update`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accessLevel})}); await Promise.all([loadMembers(),loadLogs()]); toast(accessLevel==='vip'?'已調整為 VIP 會員':'已調整為一般會員','ok'); }
async function changePassword(id){ const password=await askText('修改會員密碼','新密碼','','請直接輸入新的會員密碼。','password','更新密碼'); if(!password) return; await api(`/api/admin/members/${id}/update`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})}); toast('會員密碼已更新','ok'); await loadLogs(); }

async function changeDeviceLimit(id,current){
  const picked = await showActionModal({ title:'調整設備上限', bodyHtml:`<div><label>設備上限</label><select id="deviceLimitSelect"><option value="3" ${Number(current||3)===3?'selected' : ''}>3 台</option><option value="5" ${Number(current||3)===5?'selected' : ''}>5 台</option><option value="8" ${Number(current||3)===8?'selected' : ''}>8 台</option><option value="10" ${Number(current||3)===10?'selected' : ''}>10 台</option></select><div class="actionHelp">可隨時切換成 3 / 5 / 8 / 10，方便管理一般會員與 VIP 會員權益。</div></div>`, confirmText:'儲存設定', onConfirm:()=>{ const value=Number($('deviceLimitSelect').value||current||3); if(![3,5,8,10].includes(value)) throw new Error('設備上限只能設定為 3 / 5 / 8 / 10'); return {value}; } });
  if(!picked) return;
  await api(`/api/admin/members/${id}/update`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceLimit:picked.value})});
  await Promise.all([loadMembers(),loadLogs()]);
  toast(`設備上限已更新為 ${picked.value} 台`,'ok');
}
async function openDevices(id){ const member=state.members.find(m=>m.id===id); state.deviceMember=member; $('deviceMemberInfo').textContent=`${member?.displayName||member?.username||''}｜目前 ${member?.deviceCount||0} / ${member?.deviceLimit||3} 台`; const data=await api(`/api/admin/members/${id}/devices`); $('devicesTbody').innerHTML=(data.devices||[]).map(d=>`<tr><td><div><b>${escapeHtml(d.deviceName||d.id)}</b></div><div class="small mono">${escapeHtml(d.id)}<br>${escapeHtml((d.userAgent||'').slice(0,90))}</div></td><td>${escapeHtml(fmt(d.firstLoginAt))}</td><td>${escapeHtml(fmt(d.lastSeenAt))}</td><td><div>${escapeHtml(ipLabel(d.lastIp))}</div><div class="small mono">${escapeHtml(d.lastIp||'—')}</div></td><td><div class="btns"><button onclick="renameDevice('${id}','${d.id}')">改名</button><button class="warn" onclick="removeDevice('${id}','${d.id}')">移除</button></div></td></tr>`).join('')||'<tr><td colspan="5" class="small">沒有綁定設備</td></tr>'; $('deviceModal').classList.add('show'); }
async function renameDevice(memberId,deviceId){ const deviceName=await askText('調整設備名稱','設備名稱','','例如：小男 iPhone / 公司桌機','text','儲存名稱'); if(!deviceName) return; await api(`/api/admin/members/${memberId}/devices/rename`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceId,deviceName})}); await openDevices(memberId); await Promise.all([loadMembers(),loadLogs()]); toast('設備名稱已更新','ok'); }
async function removeDevice(memberId,deviceId){ const ok=await showActionModal({ title:'移除設備', bodyHtml:'<div class="actionHelp">這台設備會從綁定清單移除，會員之後可重新綁定新設備。</div>', confirmText:'確認移除', onConfirm:()=>true }); if(!ok) return; await api(`/api/admin/members/${memberId}/devices/remove`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceId})}); await openDevices(memberId); await Promise.all([loadMembers(),loadLogs()]); toast('設備已移除','ok'); }
async function clearDevices(){ if(!state.deviceMember) return; const ok=await showActionModal({ title:'清空全部設備', bodyHtml:'<div class="actionHelp">確定要清空此會員所有綁定設備嗎？清空後該會員可重新綁定新設備。</div>', confirmText:'確認清空', onConfirm:()=>true }); if(!ok) return; await api(`/api/admin/members/${state.deviceMember.id}/devices/clear`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}); $('deviceModal').classList.remove('show'); await Promise.all([loadMembers(),loadLogs()]); toast('已清空此會員全部設備','ok'); }
document.addEventListener('DOMContentLoaded',()=>{ $('loginBtn').addEventListener('click',login); $('loginUsername').addEventListener('keydown',e=>{if(e.key==='Enter')login()}); $('loginPassword').addEventListener('keydown',e=>{if(e.key==='Enter')login()}); $('logoutBtn').addEventListener('click',logout); $('createMemberBtn').addEventListener('click',()=>createMember().then(()=>toast('會員已新增','ok')).catch(err=>toast(err.message,'warn'))); $('reloadMembersBtn').addEventListener('click',()=>loadMembers().then(()=>toast('會員資料已更新','info')).catch(err=>toast(err.message,'warn'))); $('generateKeysBtn').addEventListener('click',()=>generateKeys().then(()=>toast('金鑰已生成','ok')).catch(err=>toast(err.message,'warn'))); $('reloadKeysBtn').addEventListener('click',()=>loadKeys().then(()=>toast('金鑰列表已更新','info')).catch(err=>toast(err.message,'warn'))); $('reloadLogsBtn').addEventListener('click',()=>loadLogs().then(()=>toast('操作日誌已更新','info')).catch(err=>toast(err.message,'warn'))); $('redeemBtn').addEventListener('click',()=>redeem().then(()=>toast('金鑰已套用到會員','ok')).catch(err=>toast(err.message,'warn'))); $('closeDeviceModal').addEventListener('click',()=>$('deviceModal').classList.remove('show')); $('clearDevicesBtn').addEventListener('click',()=>clearDevices().catch(err=>toast(err.message,'warn'))); $('actionModal').addEventListener('click',e=>{ if(e.target.id==='actionModal') closeActionModal(); }); verify(); });
window.openDevices=openDevices; window.extendMember=extendMember; window.toggleMember=toggleMember; window.toggleVip=toggleVip; window.changePassword=changePassword; window.changeDeviceLimit=changeDeviceLimit; window.removeDevice=removeDevice; window.renameDevice=renameDevice;